config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/repo'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def repo
    @github_repo = params[:github_repo]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RobotRepo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </head>

  <body class="">
    <main class="">
      <%= render 'shared/dashboard' %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<%= render Github::UrlSearchComponent.new %>

app/views/pages/repo.html.erb
<%= params[:path] %>

app/views/shared/_dashboard.html.erb
<!-- Top Navigation Bar -->
<nav class="bg-gray-800 p-4 pl-4">
   <div class="flex">
    <h2 class="font-semibold text-xl text-white" style="padding-right: 6.7rem;">Robot Repo</h2>
    <%= render Github::UrlSearchComponent.new %>
  </div>
</nav>

<!-- Main Wrapper -->
<div class="flex">
  <!-- Side Menu -->
  <aside class="w-64 bg-gray-800 text-white p-4 min-h-screen">
    <ul class="mt-4">
      <%= render Github::RepoTreeComponent.new(git_repo: params[:github_repo], path: params[:path]) %>
    </ul>
  </aside>

  <!-- Main Content Area -->
  <main class="flex-1 p-8">
    <div>
      <%= yield %>
    </div>
  </main>
</div>

app/views/shared/_side_bar.html.erb
<div class="fixed flex flex-col top-0 left-0 w-64 bg-white h-full border-r">
  <div class="flex items-center justify-center h-14 border-b">
    <div>Robot Repo</div>
  </div>
  <div class="overflow-y-auto overflow-x-hidden flex-grow">
    <ul class="flex flex-col py-4 space-y-1">
      <li>
        <%= link_to root_path, class: "relative flex flex-row items-center h-11 focus:outline-none hover:bg-gray-50 text-gray-600 hover:text-gray-800 border-l-4 border-transparent hover:border-indigo-500 pr-6" do %>
          <span class="inline-flex justify-center items-center ml-4">
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path></svg>
          </span>
          <span class="ml-2 text-sm tracking-wide truncate">Home</span>
        <% end %>
      </li>
      <li>
        <%= link_to pages_repo_path, class: "relative flex flex-row items-center h-11 focus:outline-none hover:bg-gray-50 text-gray-600 hover:text-gray-800 border-l-4 border-transparent hover:border-indigo-500 pr-6" do %>
          <span class="inline-flex justify-center items-center ml-4">
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path></svg>
          </span>
          <span class="ml-2 text-sm tracking-wide truncate">Repo</span>
        <% end %>
      </li>
    </ul>
  </div>
</div>